# src/AppBundle/Resources/config/doctrine/Client.orm.yml
AppBundle\Entity\Client:

    type: entity
    table: client
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 45
        phone:
            type: string
            length: 45
        fax:
            type: string
            length: 45
            nullable: TRUE
        financeNumber:
            type: integer
            nullable: TRUE
        contactPerson:
            type: string
            length: 45
            nullable: TRUE
        mobile:
            type: string
            nullable: TRUE
        accContact:
            type: string
            nullable: TRUE
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
            nullable: TRUE

    oneToMany:
        proposal:
            targetEntity: Proposal
            mappedBy: client
            joinColumn:
                name: proposal_id
                referencedColumnName: id