# src/AppBundle/Resources/config/doctrine/Client.orm.yml
AppBundle\Entity\Client:

    type: entity
    table: client
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        phone:
            type: string
            length: 45
        fax:
            type: string
            length: 45
        financeNumber:
            type: integer
        contactPerson:
            type: string
            length: 45
        mobile:
            type: string
        accContact:
            type: string
        createdAt:
            type: datetime
        updatedAt:
            type: datetime