# src/AppBundle/Resources/config/doctrine/Job.orm.yml
AppBundle\Entity\Job:

    type: entity
    table: job
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        number:
            type: integer
            nullable: true
        delivery:
            type: datetime
            nullable: true
        billOfQuantities:
            type: blob
            nullable: true
        createdAt:
            type: datetime
            nullable: true
        updatedAt:
            type: datetime
            nullable: true

    oneToOne:
            vehicle:
                targetEntity: Vehicle
                inversedBy: job
                joinColumn:
                    name: vehicle_id
                    referencedColumnName: vin
            jor:
                targetEntity: JobOpeningRequest
                inversedBy: job
                joinColumn:
                    name: jor_id
                    referencedColumnName: id

            proposal:
                targetEntity: Proposal
                inversedBy: job
                joinColumn:
                    name: proposal_id
                    referencedColumnName: id