# src/AppBundle/Resources/config/doctrine/Proposal.orm.yml
AppBundle\Entity\Proposal:

    type: entity
    repositoryClass: AppBundle\Entity\ProposalRepository
    table: proposal
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        series:
            type: integer
        type:
            type: string
            length: 45
        createdAt:
            type: datetime
        updatedAt:
            type: datetime
        approvedAt:
            type: datetime
            nullable: TRUE
        proposalName:
            type: string
            nullable: TRUE
        status:
            type: integer

    manyToOne:
        client:
            targetEntity: Client
            inversedBy: proposal
            joinColumn:
                name: client_id
                referencedColumnName: id
        job:
            targetEntity: Job
            inversedBy: proposal
            joinColumn:
                name: job_id
                referencedColumnName: id