# src/AppBundle/Resources/config/doctrine/Vehicle.orm.yml
AppBundle\Entity\Vehicle:

    type: entity
    table: vehicle
    id:
        vin:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 45
        type:
            type: string
            length: 45
        createdAt:
            type: datetime
        updatedAt:
            type: datetime